[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "geodepot_api"
version = "1.0.4"
description = "geodepot API"
readme = "geodepot-py/README.md"
authors = [{ name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl" }]
requires-python = ">=3.10"
classifiers = ["Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
dev = ["ruff", "pytest"]
package = ["cibuildwheel", "twine", "uv", "build"]

[tool.scikit-build]
sdist.exclude = [".github", "geodepot-cmake", "geodepot-rs", "apps", "tests"]
wheel.exclude = [".github", "geodepot-cmake", "geodepot-rs", "apps", "tests"]
wheel.expand-macos-universal-tags = true
wheel.packages = ["geodepot-py/src/geodepot_api"]
build.verbose = true
logging.level = "INFO"
# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"
# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

[tool.scikit-build.cmake.define]
GD_BUILD_TESTING = "OFF"
GD_BUILD_APPS = "OFF"
GD_BUILD_BINDINGS = "ON"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = ["--import-mode=importlib", "-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
log_cli_level = "INFO"
filterwarnings = ["error",
    "ignore::pytest.PytestCacheWarning",
]
testpaths = ["geodepot-py/tests"]

[tool.cibuildwheel]
build-frontend = "build[uv]"
test-command = "pytest geodepot-py/tests"
test-extras = ["dev"]
archs = ["auto64"]
skip = ["pp*"] # Skip PyPy

[tool.cibuildwheel.linux]
before-build = [
    "yum install -y cmake libcurl openssl-devel",
]
repair-wheel-command = "auditwheel repair --exclude nanobind -w {dest_dir} {wheel}"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-build = [
    "apk add cmake libcurl openssl",
]

[tool.cibuildwheel.macos]
# Needed for full C++17 support on macOS
environment = { MACOSX_DEPLOYMENT_TARGET="10.14" }
before-build = [
    "brew install coreutils cmake curlpp openssl",
]

[tool.cibuildwheel.windows]
before-build = [
    "chocolatey install libcurl openssl",
]

[tool.ruff]
src = ["geodepot-py/src"]
